# General Jekyll Config
highlighter: pygments
url: http://example.com
lsi: false
exclude: [LICENSE, CNAME, README.md, .gitignore, Gemfile, Gemfile.lock]
repository: zhenyulai/zhenyulai.github.io
github: [metadata]